/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TierBandSetPropertyInner1 } from './tier-band-set-property-inner1';

/**
 * Details about the interest that may be payable to the PCA account holders
 * @export
 * @interface CreditInterestProperty1
 */
export interface CreditInterestProperty1 {
    /**
     * The group of tiers or bands for which credit interest can be applied.
     * @type {Array<TierBandSetPropertyInner1>}
     * @memberof CreditInterestProperty1
     */
    'TierBandSet': Array<TierBandSetPropertyInner1>;
}

