/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeeApplicableRangeProperty } from './fee-applicable-range-property';
import { FeeChargeCapPropertyInner } from './fee-charge-cap-property-inner';
import { OtherApplicationFrequencyProperty3 } from './other-application-frequency-property3';
import { OtherCalculationFrequencyProperty3 } from './other-calculation-frequency-property3';
import { OtherFeeCategoryTypeProperty } from './other-fee-category-type-property';
import { OtherFeeRateTypeProperty2 } from './other-fee-rate-type-property2';
import { OtherFeeTypeProperty2 } from './other-fee-type-property2';

/**
 * Other fees/charges details
 * @export
 * @interface FeeChargeDetailPropertyInner
 */
export interface FeeChargeDetailPropertyInner {
    /**
     * Categorisation of fees and charges into standard categories.
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeCategory': FeeChargeDetailPropertyInnerFeeCategoryEnum;
    /**
     * Fee/Charge Type
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeType': FeeChargeDetailPropertyInnerFeeTypeEnum;
    /**
     * Fee/charge which is usually negotiable rather than a fixed amount
     * @type {boolean}
     * @memberof FeeChargeDetailPropertyInner
     */
    'NegotiableIndicator'?: boolean;
    /**
     * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeRate'?: string;
    /**
     * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeRateType'?: FeeChargeDetailPropertyInnerFeeRateTypeEnum;
    /**
     * How frequently the fee/charge is applied to the account
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'ApplicationFrequency': FeeChargeDetailPropertyInnerApplicationFrequencyEnum;
    /**
     * How frequently the fee/charge is calculated
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner
     */
    'CalculationFrequency'?: FeeChargeDetailPropertyInnerCalculationFrequencyEnum;
    /**
     * Optional additional notes to supplement the fee/charge details.
     * @type {Array<string>}
     * @memberof FeeChargeDetailPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * Details about any caps (maximum charges) that apply to a particular or group of fee/charge
     * @type {Array<FeeChargeCapPropertyInner>}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeChargeCap'?: Array<FeeChargeCapPropertyInner>;
    /**
     * 
     * @type {OtherFeeCategoryTypeProperty}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherFeeCategoryType'?: OtherFeeCategoryTypeProperty;
    /**
     * 
     * @type {OtherFeeTypeProperty2}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherFeeType'?: OtherFeeTypeProperty2;
    /**
     * 
     * @type {OtherFeeRateTypeProperty2}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty2;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty3}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty3;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty3}
     * @memberof FeeChargeDetailPropertyInner
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty3;
    /**
     * 
     * @type {FeeApplicableRangeProperty}
     * @memberof FeeChargeDetailPropertyInner
     */
    'FeeApplicableRange'?: FeeApplicableRangeProperty;
}

type FeeChargeDetailPropertyInnerFeeCategoryEnum = 'Other' | 'Servicing'
type FeeChargeDetailPropertyInnerFeeTypeEnum = 'Other' | 'ServiceCAccountFee' | 'ServiceCAccountFeeMonthly' | 'ServiceCAccountFeeQuarterly' | 'ServiceCFixedTariff' | 'ServiceCBusiDepAccBreakage' | 'ServiceCMinimumMonthlyFee' | 'ServiceCOther'
type FeeChargeDetailPropertyInnerFeeRateTypeEnum = 'Gross' | 'Other'
type FeeChargeDetailPropertyInnerApplicationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type FeeChargeDetailPropertyInnerCalculationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'


