/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeeApplicableRangeProperty1 } from './fee-applicable-range-property1';
import { FeeChargeCapPropertyInner2 } from './fee-charge-cap-property-inner2';
import { OtherApplicationFrequencyProperty7 } from './other-application-frequency-property7';
import { OtherCalculationFrequencyProperty7 } from './other-calculation-frequency-property7';
import { OtherFeeCategoryTypeProperty1 } from './other-fee-category-type-property1';
import { OtherFeeRateTypeProperty5 } from './other-fee-rate-type-property5';
import { OtherFeeTypeProperty5 } from './other-fee-type-property5';

/**
 * Other fees/charges details
 * @export
 * @interface FeeChargeDetailPropertyInner1
 */
export interface FeeChargeDetailPropertyInner1 {
    /**
     * Categorisation of fees and charges into standard categories.
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeCategory': FeeChargeDetailPropertyInner1FeeCategoryEnum;
    /**
     * Fee/Charge Type
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeType': FeeChargeDetailPropertyInner1FeeTypeEnum;
    /**
     * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeRate'?: string;
    /**
     * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeRateType'?: FeeChargeDetailPropertyInner1FeeRateTypeEnum;
    /**
     * How frequently the fee/charge is applied to the account
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'ApplicationFrequency': FeeChargeDetailPropertyInner1ApplicationFrequencyEnum;
    /**
     * How frequently the fee/charge is calculated
     * @type {string}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'CalculationFrequency'?: FeeChargeDetailPropertyInner1CalculationFrequencyEnum;
    /**
     * Optional additional notes to supplement the fee/charge details.
     * @type {Array<string>}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherFeeCategoryTypeProperty1}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherFeeCategoryType'?: OtherFeeCategoryTypeProperty1;
    /**
     * 
     * @type {OtherFeeTypeProperty5}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherFeeType'?: OtherFeeTypeProperty5;
    /**
     * 
     * @type {OtherFeeRateTypeProperty5}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty5;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty7}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty7;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty7}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty7;
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge
     * @type {Array<FeeChargeCapPropertyInner2>}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeChargeCap'?: Array<FeeChargeCapPropertyInner2>;
    /**
     * 
     * @type {FeeApplicableRangeProperty1}
     * @memberof FeeChargeDetailPropertyInner1
     */
    'FeeApplicableRange'?: FeeApplicableRangeProperty1;
}

type FeeChargeDetailPropertyInner1FeeCategoryEnum = 'Other' | 'Servicing'
type FeeChargeDetailPropertyInner1FeeTypeEnum = 'ServiceCAccountFee' | 'ServiceCAccountFeeMonthly' | 'ServiceCOther' | 'Other'
type FeeChargeDetailPropertyInner1FeeRateTypeEnum = 'LinkedBaseRate' | 'Gross' | 'Net' | 'Other'
type FeeChargeDetailPropertyInner1ApplicationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type FeeChargeDetailPropertyInner1CalculationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'


