/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBAccountStatus1Code } from './obaccount-status1-code';
import { OBExternalAccountSubType1Code } from './obexternal-account-sub-type1-code';
import { OBExternalAccountType1Code } from './obexternal-account-type1-code';
import { OBExternalSwitchStatusCode } from './obexternal-switch-status-code';

/**
 * Unambiguous identification of the account to which credit and debit entries are made.
 * @export
 * @interface OBAccount6Basic
 */
export interface OBAccount6Basic {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBAccount6Basic
     */
    'AccountId': string;
    /**
     * Specifies the status of account resource in code form.
     * @type {OBAccountStatus1Code}
     * @memberof OBAccount6Basic
     */
    'Status'?: OBAccountStatus1Code;
    /**
     * Date and time at which the resource status was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBAccount6Basic
     */
    'StatusUpdateDateTime'?: string;
    /**
     * Identification of the currency in which the account is held.  Usage: Currency should only be used in case one and the same account number covers several currencies and the initiating party needs to identify which currency needs to be used for settlement on the account.
     * @type {string}
     * @memberof OBAccount6Basic
     */
    'Currency': string;
    /**
     * Specifies the type of account (personal or business).
     * @type {OBExternalAccountType1Code}
     * @memberof OBAccount6Basic
     */
    'AccountType': OBExternalAccountType1Code;
    /**
     * Specifies the sub type of account (product family group).
     * @type {OBExternalAccountSubType1Code}
     * @memberof OBAccount6Basic
     */
    'AccountSubType': OBExternalAccountSubType1Code;
    /**
     * Specifies the description of the account type.
     * @type {string}
     * @memberof OBAccount6Basic
     */
    'Description'?: string;
    /**
     * The nickname of the account, assigned by the account owner in order to provide an additional means of identification of the account.
     * @type {string}
     * @memberof OBAccount6Basic
     */
    'Nickname'?: string;
    /**
     * Date on which the account and related basic services are effectively operational for the account owner.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBAccount6Basic
     */
    'OpeningDate'?: string;
    /**
     * Maturity date of the account.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBAccount6Basic
     */
    'MaturityDate'?: string;
    /**
     * Specifies the switch status for the account, in a coded form.
     * @type {OBExternalSwitchStatusCode}
     * @memberof OBAccount6Basic
     */
    'SwitchStatus'?: OBExternalSwitchStatusCode;
}

