/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Set of elements used to fully identify the type of underlying transaction resulting in an entry.
 * @export
 * @interface OBBankTransactionCodeStructure1
 */
export interface OBBankTransactionCodeStructure1 {
    /**
     * Specifies the family within a domain.
     * @type {string}
     * @memberof OBBankTransactionCodeStructure1
     */
    'Code': string;
    /**
     * Specifies the sub-product family within a specific family.
     * @type {string}
     * @memberof OBBankTransactionCodeStructure1
     */
    'SubCode': string;
}

