/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBBeneficiaryType1Code } from './obbeneficiary-type1-code';
import { OBBranchAndFinancialInstitutionIdentification60 } from './obbranch-and-financial-institution-identification60';
import { OBCashAccount50 } from './obcash-account50';

/**
 * TO DO
 * @export
 * @interface OBBeneficiary5
 */
export interface OBBeneficiary5 {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBBeneficiary5
     */
    'AccountId'?: string;
    /**
     * A unique and immutable identifier used to identify the beneficiary resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBBeneficiary5
     */
    'BeneficiaryId'?: string;
    /**
     * Specifies the Beneficiary Type.
     * @type {OBBeneficiaryType1Code}
     * @memberof OBBeneficiary5
     */
    'BeneficiaryType'?: OBBeneficiaryType1Code;
    /**
     * Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction. Usage: If available, the initiating party should provide this reference in the structured remittance information, to enable reconciliation by the creditor upon receipt of the amount of money. If the business context requires the use of a creditor reference or a payment remit identification, and only one identifier can be passed through the end-to-end chain, the creditor\'s reference or payment remittance identification should be quoted in the end-to-end transaction identification.
     * @type {string}
     * @memberof OBBeneficiary5
     */
    'Reference'?: string;
    /**
     * Additional information that can not be captured in the structured fields and/or any other specific block.
     * @type {{ [key: string]: any; }}
     * @memberof OBBeneficiary5
     */
    'SupplementaryData'?: { [key: string]: any; };
    /**
     * 
     * @type {OBBranchAndFinancialInstitutionIdentification60}
     * @memberof OBBeneficiary5
     */
    'CreditorAgent'?: OBBranchAndFinancialInstitutionIdentification60;
    /**
     * 
     * @type {OBCashAccount50}
     * @memberof OBBeneficiary5
     */
    'CreditorAccount'?: OBCashAccount50;
}

