/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBError1 } from './oberror1';

/**
 * An array of detail error codes, and messages, and URLs to documentation to help remediation.
 * @export
 * @interface OBErrorResponse1
 */
export interface OBErrorResponse1 {
    /**
     * High level textual error code, to help categorize the errors.
     * @type {string}
     * @memberof OBErrorResponse1
     */
    'Code': string;
    /**
     * A unique reference for the error instance, for audit purposes, in case of unknown/unclassified errors.
     * @type {string}
     * @memberof OBErrorResponse1
     */
    'Id'?: string;
    /**
     * Brief Error message, e.g., \'There is something wrong with the request parameters provided\'
     * @type {string}
     * @memberof OBErrorResponse1
     */
    'Message': string;
    /**
     * 
     * @type {Array<OBError1>}
     * @memberof OBErrorResponse1
     */
    'Errors': Array<OBError1>;
}

