/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBAddressTypeCode } from './obaddress-type-code';

/**
 * Postal address of a party.
 * @export
 * @interface OBParty2AddressInner
 */
export interface OBParty2AddressInner {
    /**
     * Identifies the nature of the postal address.
     * @type {OBAddressTypeCode}
     * @memberof OBParty2AddressInner
     */
    'AddressType'?: OBAddressTypeCode;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBParty2AddressInner
     */
    'AddressLine'?: Array<string>;
    /**
     * Name of a street or thoroughfare.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'StreetName'?: string;
    /**
     * Number that identifies the position of a building on a street.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'BuildingNumber'?: string;
    /**
     * Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'PostCode'?: string;
    /**
     * Name of a built-up area, with defined boundaries, and a local government.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'TownName'?: string;
    /**
     * Identifies a subdivision of a country eg, state, region, county.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'CountrySubDivision'?: string;
    /**
     * Nation with its own government, occupying a particular territory.
     * @type {string}
     * @memberof OBParty2AddressInner
     */
    'Country': string;
}

