/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBAddressTypeCode } from './obaddress-type-code';

/**
 * Information that locates and identifies a specific address, as defined by postal services.
 * @export
 * @interface OBPostalAddress6
 */
export interface OBPostalAddress6 {
    /**
     * Identifies the nature of the postal address.
     * @type {OBAddressTypeCode}
     * @memberof OBPostalAddress6
     */
    'AddressType'?: OBAddressTypeCode;
    /**
     * Identification of a division of a large organisation or building.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'Department'?: string;
    /**
     * Identification of a sub-division of a large organisation or building.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'SubDepartment'?: string;
    /**
     * Name of a street or thoroughfare.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'StreetName'?: string;
    /**
     * Number that identifies the position of a building on a street.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'BuildingNumber'?: string;
    /**
     * Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'PostCode'?: string;
    /**
     * Name of a built-up area, with defined boundaries, and a local government.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'TownName'?: string;
    /**
     * Identifies a subdivision of a country such as state, region, county.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'CountrySubDivision'?: string;
    /**
     * Nation with its own government.
     * @type {string}
     * @memberof OBPostalAddress6
     */
    'Country'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBPostalAddress6
     */
    'AddressLine'?: Array<string>;
}

