/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount0 } from './obactive-or-historic-currency-and-amount0';
import { OBExternalDirectDebitStatus1Code } from './obexternal-direct-debit-status1-code';

/**
 * Account to or from which a cash entry is made.
 * @export
 * @interface OBReadDirectDebit2DataDirectDebitInner
 */
export interface OBReadDirectDebit2DataDirectDebitInner {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'AccountId': string;
    /**
     * A unique and immutable identifier used to identify the direct debit resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'DirectDebitId'?: string;
    /**
     * Direct Debit reference. For AUDDIS service users provide Core Reference. For non AUDDIS service users provide Core reference if possible or last used reference.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'MandateIdentification': string;
    /**
     * Specifies the status of the direct debit in code form.
     * @type {OBExternalDirectDebitStatus1Code}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'DirectDebitStatusCode'?: OBExternalDirectDebitStatus1Code;
    /**
     * Name of Service User.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'Name': string;
    /**
     * Date of most recent direct debit collection.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'PreviousPaymentDateTime'?: string;
    /**
     * Regularity with which direct debit instructions are to be created and processed.
     * @type {string}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'Frequency'?: OBReadDirectDebit2DataDirectDebitInnerFrequencyEnum;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount0}
     * @memberof OBReadDirectDebit2DataDirectDebitInner
     */
    'PreviousPaymentAmount'?: OBActiveOrHistoricCurrencyAndAmount0;
}

type OBReadDirectDebit2DataDirectDebitInnerFrequencyEnum = 'UK.OBIE.Annual' | 'UK.OBIE.Daily' | 'UK.OBIE.Fortnightly' | 'UK.OBIE.HalfYearly' | 'UK.OBIE.Monthly' | 'UK.OBIE.NotKnown' | 'UK.OBIE.Quarterly' | 'UK.OBIE.Weekly'


