/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadBalance1DataBalanceInnerCreditLineInnerAmount } from './obread-balance1-data-balance-inner-credit-line-inner-amount';

/**
 * Set of elements used to provide details on the credit line.
 * @export
 * @interface OBReadBalance1DataBalanceInnerCreditLineInner
 */
export interface OBReadBalance1DataBalanceInnerCreditLineInner {
    /**
     * Indicates whether or not the credit line is included in the balance of the account. Usage: If not present, credit line is not included in the balance amount of the account.
     * @type {boolean}
     * @memberof OBReadBalance1DataBalanceInnerCreditLineInner
     */
    'Included': boolean;
    /**
     * Limit type, in a coded form.
     * @type {string}
     * @memberof OBReadBalance1DataBalanceInnerCreditLineInner
     */
    'Type'?: OBReadBalance1DataBalanceInnerCreditLineInnerTypeEnum;
    /**
     * 
     * @type {OBReadBalance1DataBalanceInnerCreditLineInnerAmount}
     * @memberof OBReadBalance1DataBalanceInnerCreditLineInner
     */
    'Amount'?: OBReadBalance1DataBalanceInnerCreditLineInnerAmount;
}

type OBReadBalance1DataBalanceInnerCreditLineInnerTypeEnum = 'Available' | 'Credit' | 'Emergency' | 'Pre-Agreed' | 'Temporary'


