/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBFeeFrequency1Code0 } from './obfee-frequency1-code0';
import { OBFeeFrequency1Code1 } from './obfee-frequency1-code1';
import { OBInterestRateType1Code0 } from './obinterest-rate-type1-code0';
import { OBOtherCodeType11 } from './obother-code-type11';
import { OBOtherCodeType12 } from './obother-code-type12';
import { OBOtherCodeType13 } from './obother-code-type13';
import { OBOtherCodeType14 } from './obother-code-type14';
import { OBOverdraftFeeType1Code } from './oboverdraft-fee-type1-code';
import { OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeCapInner } from './obread-product2-data-product-inner-other-product-type-overdraft-overdraft-tier-band-set-inner-overdraft-tier-band-inner-overdraft-fees-charges-inner-overdraft-fee-charge-cap-inner';

/**
 * Details about the fees/charges
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner {
    /**
     * Overdraft fee type
     * @type {OBOverdraftFeeType1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeType': OBOverdraftFeeType1Code;
    /**
     * Indicates whether fee and charges are negotiable
     * @type {boolean}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'NegotiableIndicator'?: boolean;
    /**
     * Indicates if the fee/charge is already covered by an \'Overdraft Control\' fee or not.
     * @type {boolean}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OverdraftControlIndicator'?: boolean;
    /**
     * Every additional tranche of an overdraft balance to which an overdraft fee is applied
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'IncrementalBorrowingAmount'?: string;
    /**
     * Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeRate'?: string;
    /**
     * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {OBInterestRateType1Code0}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'FeeRateType'?: OBInterestRateType1Code0;
    /**
     * Frequency at which the overdraft charge is applied to the account
     * @type {OBFeeFrequency1Code0}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'ApplicationFrequency': OBFeeFrequency1Code0;
    /**
     * How often is the overdraft fee/charge calculated for the account.
     * @type {OBFeeFrequency1Code1}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'CalculationFrequency'?: OBFeeFrequency1Code1;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeCapInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OverdraftFeeChargeCap'?: Array<OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeCapInner>;
    /**
     * 
     * @type {OBOtherCodeType13}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherFeeType'?: OBOtherCodeType13;
    /**
     * 
     * @type {OBOtherCodeType14}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherFeeRateType'?: OBOtherCodeType14;
    /**
     * 
     * @type {OBOtherCodeType11}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherApplicationFrequency'?: OBOtherCodeType11;
    /**
     * 
     * @type {OBOtherCodeType12}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOverdraftOverdraftTierBandSetInnerOverdraftTierBandInnerOverdraftFeesChargesInnerOverdraftFeeChargeDetailInner
     */
    'OtherCalculationFrequency'?: OBOtherCodeType12;
}

