/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBFeeFrequency1Code2 } from './obfee-frequency1-code2';
import { OBFeeFrequency1Code3 } from './obfee-frequency1-code3';
import { OBFeeType1Code } from './obfee-type1-code';
import { OBInterestRateType1Code1 } from './obinterest-rate-type1-code1';
import { OBOtherCodeType16 } from './obother-code-type16';
import { OBOtherCodeType17 } from './obother-code-type17';
import { OBOtherCodeType18 } from './obother-code-type18';
import { OBOtherFeeChargeDetailType } from './obother-fee-charge-detail-type';

/**
 * Details about specific fees/charges that are applied for repayment
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner {
    /**
     * Fee/Charge Type
     * @type {OBFeeType1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'FeeType': OBFeeType1Code;
    /**
     * Fee/charge which is usually negotiable rather than a fixed amount
     * @type {boolean}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'NegotiableIndicator'?: boolean;
    /**
     * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'FeeRate'?: string;
    /**
     * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {OBInterestRateType1Code1}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'FeeRateType'?: OBInterestRateType1Code1;
    /**
     * How frequently the fee/charge is applied to the account
     * @type {OBFeeFrequency1Code2}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'ApplicationFrequency': OBFeeFrequency1Code2;
    /**
     * How frequently the fee/charge is calculated
     * @type {OBFeeFrequency1Code3}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'CalculationFrequency': OBFeeFrequency1Code3;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBOtherFeeChargeDetailType}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'OtherFeeType'?: OBOtherFeeChargeDetailType;
    /**
     * 
     * @type {OBOtherCodeType18}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'OtherFeeRateType'?: OBOtherCodeType18;
    /**
     * 
     * @type {OBOtherCodeType16}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'OtherApplicationFrequency'?: OBOtherCodeType16;
    /**
     * 
     * @type {OBOtherCodeType17}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    'OtherCalculationFrequency'?: OBOtherCodeType17;
}

