/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadProduct2DataProductInnerOtherProductTypeCreditInterest } from './obread-product2-data-product-inner-other-product-type-credit-interest';
import { OBReadProduct2DataProductInnerOtherProductTypeLoanInterest } from './obread-product2-data-product-inner-other-product-type-loan-interest';
import { OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInner } from './obread-product2-data-product-inner-other-product-type-other-fees-charges-inner';
import { OBReadProduct2DataProductInnerOtherProductTypeOverdraft } from './obread-product2-data-product-inner-other-product-type-overdraft';
import { OBReadProduct2DataProductInnerOtherProductTypeProductDetails } from './obread-product2-data-product-inner-other-product-type-product-details';
import { OBReadProduct2DataProductInnerOtherProductTypeRepayment } from './obread-product2-data-product-inner-other-product-type-repayment';

/**
 * Other product type details associated with the account.
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductType
 */
export interface OBReadProduct2DataProductInnerOtherProductType {
    /**
     * Long name associated with the product
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Name': string;
    /**
     * Description of the Product associated with the account
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Description': string;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeProductDetails}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'ProductDetails'?: OBReadProduct2DataProductInnerOtherProductTypeProductDetails;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeCreditInterest}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'CreditInterest'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterest;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeOverdraft}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Overdraft'?: OBReadProduct2DataProductInnerOtherProductTypeOverdraft;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeLoanInterest}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'LoanInterest'?: OBReadProduct2DataProductInnerOtherProductTypeLoanInterest;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeRepayment}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'Repayment'?: OBReadProduct2DataProductInnerOtherProductTypeRepayment;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'OtherFeesCharges'?: Array<OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInner>;
    /**
     * Additional information that can not be captured in the structured fields and/or any other specific block.
     * @type {{ [key: string]: any; }}
     * @memberof OBReadProduct2DataProductInnerOtherProductType
     */
    'SupplementaryData'?: { [key: string]: any; };
}

