/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBFeeCategory1Code } from './obfee-category1-code';
import { OBFeeFrequency1Code2 } from './obfee-frequency1-code2';
import { OBFeeFrequency1Code3 } from './obfee-frequency1-code3';
import { OBFeeType1Code } from './obfee-type1-code';
import { OBInterestRateType1Code1 } from './obinterest-rate-type1-code1';
import { OBOtherCodeType10 } from './obother-code-type10';
import { OBOtherCodeType16 } from './obother-code-type16';
import { OBOtherCodeType17 } from './obother-code-type17';
import { OBOtherCodeType18 } from './obother-code-type18';
import { OBOtherFeeChargeDetailType } from './obother-fee-charge-detail-type';
import { OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInnerFeeApplicableRange } from './obread-product2-data-product-inner-other-product-type-other-fees-charges-inner-fee-charge-detail-inner-fee-applicable-range';
import { OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInnerFeeChargeCapInner } from './obread-product2-data-product-inner-other-product-type-other-fees-charges-inner-fee-charge-detail-inner-fee-charge-cap-inner';

/**
 * Other fees/charges details
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner {
    /**
     * Categorisation of fees and charges into standard categories.
     * @type {OBFeeCategory1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'FeeCategory': OBFeeCategory1Code;
    /**
     * Fee/Charge Type
     * @type {OBFeeType1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'FeeType': OBFeeType1Code;
    /**
     * Fee/charge which is usually negotiable rather than a fixed amount
     * @type {boolean}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'NegotiableIndicator'?: boolean;
    /**
     * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'FeeRate'?: string;
    /**
     * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
     * @type {OBInterestRateType1Code1}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'FeeRateType'?: OBInterestRateType1Code1;
    /**
     * How frequently the fee/charge is applied to the account
     * @type {OBFeeFrequency1Code2}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'ApplicationFrequency': OBFeeFrequency1Code2;
    /**
     * How frequently the fee/charge is calculated
     * @type {OBFeeFrequency1Code3}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'CalculationFrequency'?: OBFeeFrequency1Code3;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInnerFeeChargeCapInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'FeeChargeCap'?: Array<OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInnerFeeChargeCapInner>;
    /**
     * 
     * @type {OBOtherCodeType10}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'OtherFeeCategoryType'?: OBOtherCodeType10;
    /**
     * 
     * @type {OBOtherFeeChargeDetailType}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'OtherFeeType'?: OBOtherFeeChargeDetailType;
    /**
     * 
     * @type {OBOtherCodeType18}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'OtherFeeRateType'?: OBOtherCodeType18;
    /**
     * 
     * @type {OBOtherCodeType16}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'OtherApplicationFrequency'?: OBOtherCodeType16;
    /**
     * 
     * @type {OBOtherCodeType17}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'OtherCalculationFrequency'?: OBOtherCodeType17;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInnerFeeApplicableRange}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInner
     */
    'FeeApplicableRange'?: OBReadProduct2DataProductInnerOtherProductTypeOtherFeesChargesInnerFeeChargeDetailInnerFeeApplicableRange;
}

