/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBInterestFixedVariableType1Code } from './obinterest-fixed-variable-type1-code';
import { OBOtherCodeType11 } from './obother-code-type11';
import { OBOtherCodeType12 } from './obother-code-type12';
import { OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerOtherBankInterestType } from './obread-product2-data-product-inner-other-product-type-credit-interest-tier-band-set-inner-tier-band-inner-other-bank-interest-type';

/**
 * Tier Band Details
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner {
    /**
     * Unique and unambiguous identification of a  Tier Band for the Product.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'Identification'?: string;
    /**
     * Minimum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'TierValueMinimum': string;
    /**
     * Maximum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'TierValueMaximum'?: string;
    /**
     * How often is credit interest calculated for the account.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'CalculationFrequency'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerCalculationFrequencyEnum;
    /**
     * How often is interest applied to the Product for this tier/band i.e. how often the financial institution pays accumulated interest to the customer\'s account.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'ApplicationFrequency': OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerApplicationFrequencyEnum;
    /**
     * Amount on which Interest applied.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'DepositInterestAppliedCoverage'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerDepositInterestAppliedCoverageEnum;
    /**
     * Type of interest rate, Fixed or Variable
     * @type {OBInterestFixedVariableType1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'FixedVariableInterestRateType': OBInterestFixedVariableType1Code;
    /**
     * The annual equivalent rate (AER) is interest that is calculated under the assumption that any interest paid is combined with the original balance and the next interest payment will be based on the slightly higher account balance. Overall, this means that interest can be compounded several times in a year depending on the number of times that interest payments are made.  Read more: Annual Equivalent Rate (AER) http://www.investopedia.com/terms/a/aer.asp#ixzz4gfR7IO1A
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'AER': string;
    /**
     * Interest rate types, other than AER, which financial institutions may use to describe the annual interest rate payable to the account holder\'s account.
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'BankInterestRateType'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerBankInterestRateTypeEnum;
    /**
     * Bank Interest for the product
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'BankInterestRate'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerOtherBankInterestType}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'OtherBankInterestType'?: OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerOtherBankInterestType;
    /**
     * 
     * @type {OBOtherCodeType11}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'OtherApplicationFrequency'?: OBOtherCodeType11;
    /**
     * 
     * @type {OBOtherCodeType12}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner
     */
    'OtherCalculationFrequency'?: OBOtherCodeType12;
}

type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerCalculationFrequencyEnum = 'FQAT' | 'FQDY' | 'FQHY' | 'FQMY' | 'FQOT' | 'FQQY' | 'FQSD' | 'FQWY' | 'FQYY'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerApplicationFrequencyEnum = 'FQAT' | 'FQDY' | 'FQHY' | 'FQMY' | 'FQOT' | 'FQQY' | 'FQSD' | 'FQWY' | 'FQYY'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerDepositInterestAppliedCoverageEnum = 'INBA' | 'INTI' | 'INWH'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInnerBankInterestRateTypeEnum = 'INBB' | 'INFR' | 'INGR' | 'INLR' | 'INNE' | 'INOT'


