/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Details of capital repayment holiday if any
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner {
    /**
     * The maximum length/duration of a Repayment Holiday
     * @type {number}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner
     */
    'MaxHolidayLength'?: number;
    /**
     * The unit of period (days, weeks, months etc.) of the repayment holiday
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner
     */
    'MaxHolidayPeriod'?: OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInnerMaxHolidayPeriodEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner
     */
    'Notes'?: Array<string>;
}

type OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInnerMaxHolidayPeriodEnum = 'PACT' | 'PDAY' | 'PHYR' | 'PMTH' | 'PQTR' | 'PWEK' | 'PYER'


