/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBInterestCalculationMethod1Code } from './obinterest-calculation-method1-code';
import { OBOtherCodeType10 } from './obother-code-type10';
import { OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner } from './obread-product2-data-product-inner-other-product-type-credit-interest-tier-band-set-inner-tier-band-inner';

/**
 * The group of tiers or bands for which credit interest can be applied.
 * @export
 * @interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
 */
export interface OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner {
    /**
     * The methodology of how credit interest is paid/applied. It can be:- 1. Banded Interest rates are banded. i.e. Increasing rate on whole balance as balance increases. 2. Tiered Interest rates are tiered. i.e. increasing rate for each tier as balance increases, but interest paid on tier fixed for that tier and not on whole balance. 3. Whole The same interest rate is applied irrespective of the product holder\'s account balance
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'TierBandMethod': OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandMethodEnum;
    /**
     * Methods of calculating interest
     * @type {OBInterestCalculationMethod1Code}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'CalculationMethod'?: OBInterestCalculationMethod1Code;
    /**
     * Describes whether accrued interest is payable only to the BCA or to another bank account
     * @type {string}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'Destination': OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerDestinationEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OBOtherCodeType10}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'OtherCalculationMethod'?: OBOtherCodeType10;
    /**
     * 
     * @type {OBOtherCodeType10}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'OtherDestination'?: OBOtherCodeType10;
    /**
     * 
     * @type {Array<OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner>}
     * @memberof OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInner
     */
    'TierBand': Array<OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandInner>;
}

type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerTierBandMethodEnum = 'INBA' | 'INTI' | 'INWH'
type OBReadProduct2DataProductInnerOtherProductTypeCreditInterestTierBandSetInnerDestinationEnum = 'INOT' | 'INPA' | 'INSC'


