/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBReadOffer1DataOfferInnerAmount } from './obread-offer1-data-offer-inner-amount';
import { OBReadOffer1DataOfferInnerFee } from './obread-offer1-data-offer-inner-fee';

/**
 * 
 * @export
 * @interface OBReadOffer1DataOfferInner
 */
export interface OBReadOffer1DataOfferInner {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'AccountId': string;
    /**
     * A unique and immutable identifier used to identify the offer resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'OfferId'?: string;
    /**
     * Offer type, in a coded form.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'OfferType'?: OBReadOffer1DataOfferInnerOfferTypeEnum;
    /**
     * Further details of the offer.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Description'?: string;
    /**
     * Date and time at which the offer starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'StartDateTime'?: string;
    /**
     * Date and time at which the offer ends.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'EndDateTime'?: string;
    /**
     * Rate associated with the offer type.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Rate'?: string;
    /**
     * Value associated with the offer type.
     * @type {number}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Value'?: number;
    /**
     * Further details of the term of the offer.
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Term'?: string;
    /**
     * URL (Uniform Resource Locator) where documentation on the offer can be found
     * @type {string}
     * @memberof OBReadOffer1DataOfferInner
     */
    'URL'?: string;
    /**
     * 
     * @type {OBReadOffer1DataOfferInnerAmount}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Amount'?: OBReadOffer1DataOfferInnerAmount;
    /**
     * 
     * @type {OBReadOffer1DataOfferInnerFee}
     * @memberof OBReadOffer1DataOfferInner
     */
    'Fee'?: OBReadOffer1DataOfferInnerFee;
}

type OBReadOffer1DataOfferInnerOfferTypeEnum = 'BalanceTransfer' | 'LimitIncrease' | 'MoneyTransfer' | 'Other' | 'PromotionalRate'


