/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBExternalStatementType1Code } from './obexternal-statement-type1-code';
import { OBStatement2StatementAmountInner } from './obstatement2-statement-amount-inner';
import { OBStatement2StatementBenefitInner } from './obstatement2-statement-benefit-inner';
import { OBStatement2StatementDateTimeInner } from './obstatement2-statement-date-time-inner';
import { OBStatement2StatementFeeInner } from './obstatement2-statement-fee-inner';
import { OBStatement2StatementInterestInner } from './obstatement2-statement-interest-inner';
import { OBStatement2StatementRateInner } from './obstatement2-statement-rate-inner';
import { OBStatement2StatementValueInner } from './obstatement2-statement-value-inner';

/**
 * Provides further details on a statement resource.
 * @export
 * @interface OBStatement2Detail
 */
export interface OBStatement2Detail {
    /**
     * A unique and immutable identifier used to identify the account resource. This identifier has no meaning to the account owner.
     * @type {string}
     * @memberof OBStatement2Detail
     */
    'AccountId': string;
    /**
     * Unique identifier for the statement resource within an servicing institution. This identifier is both unique and immutable.
     * @type {string}
     * @memberof OBStatement2Detail
     */
    'StatementId'?: string;
    /**
     * Unique reference for the statement. This reference may be optionally populated if available.
     * @type {string}
     * @memberof OBStatement2Detail
     */
    'StatementReference'?: string;
    /**
     * Statement type, in a coded form.
     * @type {OBExternalStatementType1Code}
     * @memberof OBStatement2Detail
     */
    'Type': OBExternalStatementType1Code;
    /**
     * Date and time at which the statement period starts.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStatement2Detail
     */
    'StartDateTime': string;
    /**
     * Date and time at which the statement period ends.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStatement2Detail
     */
    'EndDateTime': string;
    /**
     * Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStatement2Detail
     */
    'CreationDateTime': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OBStatement2Detail
     */
    'StatementDescription'?: Array<string>;
    /**
     * 
     * @type {Array<OBStatement2StatementBenefitInner>}
     * @memberof OBStatement2Detail
     */
    'StatementBenefit'?: Array<OBStatement2StatementBenefitInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementFeeInner>}
     * @memberof OBStatement2Detail
     */
    'StatementFee'?: Array<OBStatement2StatementFeeInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementInterestInner>}
     * @memberof OBStatement2Detail
     */
    'StatementInterest'?: Array<OBStatement2StatementInterestInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementAmountInner>}
     * @memberof OBStatement2Detail
     */
    'StatementAmount'?: Array<OBStatement2StatementAmountInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementDateTimeInner>}
     * @memberof OBStatement2Detail
     */
    'StatementDateTime'?: Array<OBStatement2StatementDateTimeInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementRateInner>}
     * @memberof OBStatement2Detail
     */
    'StatementRate'?: Array<OBStatement2StatementRateInner>;
    /**
     * 
     * @type {Array<OBStatement2StatementValueInner>}
     * @memberof OBStatement2Detail
     */
    'StatementValue'?: Array<OBStatement2StatementValueInner>;
}

