/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBExternalStatementDateTimeType1Code } from './obexternal-statement-date-time-type1-code';

/**
 * Set of elements used to provide details of a generic date time for the statement resource.
 * @export
 * @interface OBStatement2StatementDateTimeInner
 */
export interface OBStatement2StatementDateTimeInner {
    /**
     * Date and time associated with the date time type.All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @type {string}
     * @memberof OBStatement2StatementDateTimeInner
     */
    'DateTime': string;
    /**
     * Date time type, in a coded form.
     * @type {OBExternalStatementDateTimeType1Code}
     * @memberof OBStatement2StatementDateTimeInner
     */
    'Type': OBExternalStatementDateTimeType1Code;
}

