/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount8 } from './obactive-or-historic-currency-and-amount8';
import { OBCreditDebitCode0 } from './obcredit-debit-code0';
import { OBExternalStatementAmountType1Code } from './obexternal-statement-amount-type1-code';

/**
 * Set of elements used to provide details of a generic amount for the statement resource.
 * @export
 * @interface OBStatement2StatementAmountInner
 */
export interface OBStatement2StatementAmountInner {
    /**
     * Indicates whether the amount is a credit or a debit.  Usage: A zero amount is considered to be a credit amount.
     * @type {OBCreditDebitCode0}
     * @memberof OBStatement2StatementAmountInner
     */
    'CreditDebitIndicator': OBCreditDebitCode0;
    /**
     * Amount type, in a coded form.
     * @type {OBExternalStatementAmountType1Code}
     * @memberof OBStatement2StatementAmountInner
     */
    'Type': OBExternalStatementAmountType1Code;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount8}
     * @memberof OBStatement2StatementAmountInner
     */
    'Amount': OBActiveOrHistoricCurrencyAndAmount8;
}

