/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount6 } from './obactive-or-historic-currency-and-amount6';
import { OBCreditDebitCode0 } from './obcredit-debit-code0';
import { OBExternalStatementFeeFrequency1Code } from './obexternal-statement-fee-frequency1-code';
import { OBExternalStatementFeeRateType1Code } from './obexternal-statement-fee-rate-type1-code';
import { OBExternalStatementFeeType1Code } from './obexternal-statement-fee-type1-code';

/**
 * Set of elements used to provide details of a fee for the statement resource.
 * @export
 * @interface OBStatement2StatementFeeInner
 */
export interface OBStatement2StatementFeeInner {
    /**
     * Description that may be available for the statement fee.
     * @type {string}
     * @memberof OBStatement2StatementFeeInner
     */
    'Description'?: string;
    /**
     * Indicates whether the amount is a credit or a debit.  Usage: A zero amount is considered to be a credit amount.
     * @type {OBCreditDebitCode0}
     * @memberof OBStatement2StatementFeeInner
     */
    'CreditDebitIndicator': OBCreditDebitCode0;
    /**
     * Fee type, in a coded form.
     * @type {OBExternalStatementFeeType1Code}
     * @memberof OBStatement2StatementFeeInner
     */
    'Type': OBExternalStatementFeeType1Code;
    /**
     * Rate charged for Statement Fee (where it is charged in terms of a rate rather than an amount)
     * @type {number}
     * @memberof OBStatement2StatementFeeInner
     */
    'Rate'?: number;
    /**
     * Description that may be available for the statement fee rate type.
     * @type {OBExternalStatementFeeRateType1Code}
     * @memberof OBStatement2StatementFeeInner
     */
    'RateType'?: OBExternalStatementFeeRateType1Code;
    /**
     * How frequently the fee is applied to the Account.
     * @type {OBExternalStatementFeeFrequency1Code}
     * @memberof OBStatement2StatementFeeInner
     */
    'Frequency'?: OBExternalStatementFeeFrequency1Code;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount6}
     * @memberof OBStatement2StatementFeeInner
     */
    'Amount': OBActiveOrHistoricCurrencyAndAmount6;
}

