/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBActiveOrHistoricCurrencyAndAmount7 } from './obactive-or-historic-currency-and-amount7';
import { OBCreditDebitCode0 } from './obcredit-debit-code0';
import { OBExternalStatementInterestFrequency1Code } from './obexternal-statement-interest-frequency1-code';
import { OBExternalStatementInterestRateType1Code } from './obexternal-statement-interest-rate-type1-code';
import { OBExternalStatementInterestType1Code } from './obexternal-statement-interest-type1-code';

/**
 * Set of elements used to provide details of a generic interest amount related to the statement resource.
 * @export
 * @interface OBStatement2StatementInterestInner
 */
export interface OBStatement2StatementInterestInner {
    /**
     * Description that may be available for the statement interest.
     * @type {string}
     * @memberof OBStatement2StatementInterestInner
     */
    'Description'?: string;
    /**
     * Indicates whether the amount is a credit or a debit.  Usage: A zero amount is considered to be a credit amount.
     * @type {OBCreditDebitCode0}
     * @memberof OBStatement2StatementInterestInner
     */
    'CreditDebitIndicator': OBCreditDebitCode0;
    /**
     * Interest amount type, in a coded form.
     * @type {OBExternalStatementInterestType1Code}
     * @memberof OBStatement2StatementInterestInner
     */
    'Type': OBExternalStatementInterestType1Code;
    /**
     * field representing a percentage (e.g. 0.05 represents 5% and 0.9525 represents 95.25%). Note the number of decimal places may vary.
     * @type {number}
     * @memberof OBStatement2StatementInterestInner
     */
    'Rate'?: number;
    /**
     * Description that may be available for the statement Interest rate type.
     * @type {OBExternalStatementInterestRateType1Code}
     * @memberof OBStatement2StatementInterestInner
     */
    'RateType'?: OBExternalStatementInterestRateType1Code;
    /**
     * Specifies the statement fee type requested
     * @type {OBExternalStatementInterestFrequency1Code}
     * @memberof OBStatement2StatementInterestInner
     */
    'Frequency'?: OBExternalStatementInterestFrequency1Code;
    /**
     * 
     * @type {OBActiveOrHistoricCurrencyAndAmount7}
     * @memberof OBStatement2StatementInterestInner
     */
    'Amount': OBActiveOrHistoricCurrencyAndAmount7;
}

