/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Set of elements to describe the card instrument used in the transaction.
 * @export
 * @interface OBTransactionCardInstrument1
 */
export interface OBTransactionCardInstrument1 {
    /**
     * Name of the card scheme.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'CardSchemeName': OBTransactionCardInstrument1CardSchemeNameEnum;
    /**
     * The card authorisation type.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'AuthorisationType'?: OBTransactionCardInstrument1AuthorisationTypeEnum;
    /**
     * Name of the cardholder using the card instrument.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'Name'?: string;
    /**
     * Identification assigned by an institution to identify the card instrument used in the transaction. This identification is known by the account owner, and may be masked.
     * @type {string}
     * @memberof OBTransactionCardInstrument1
     */
    'Identification'?: string;
}

type OBTransactionCardInstrument1CardSchemeNameEnum = 'AmericanExpress' | 'Diners' | 'Discover' | 'MasterCard' | 'VISA'
type OBTransactionCardInstrument1AuthorisationTypeEnum = 'ConsumerDevice' | 'Contactless' | 'None' | 'PIN'


