/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OBBalanceType1Code } from './obbalance-type1-code';
import { OBCreditDebitCode2 } from './obcredit-debit-code2';
import { OBTransactionCashBalanceAmount } from './obtransaction-cash-balance-amount';

/**
 * Set of elements used to define the balance as a numerical representation of the net increases and decreases in an account after a transaction entry is applied to the account.
 * @export
 * @interface OBTransactionCashBalance
 */
export interface OBTransactionCashBalance {
    /**
     * Indicates whether the balance is a credit or a debit balance.  Usage: A zero balance is considered to be a credit balance.
     * @type {OBCreditDebitCode2}
     * @memberof OBTransactionCashBalance
     */
    'CreditDebitIndicator': OBCreditDebitCode2;
    /**
     * Balance type, in a coded form.
     * @type {OBBalanceType1Code}
     * @memberof OBTransactionCashBalance
     */
    'Type': OBBalanceType1Code;
    /**
     * 
     * @type {OBTransactionCashBalanceAmount}
     * @memberof OBTransactionCashBalance
     */
    'Amount': OBTransactionCashBalanceAmount;
}

