/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeeChargeCapPropertyInner1 } from './fee-charge-cap-property-inner1';
import { FeeChargeDetailPropertyInner } from './fee-charge-detail-property-inner';
import { OtherTariffTypeProperty } from './other-tariff-type-property';

/**
 * Contains details of fees and charges which are not associated with either Overdraft or features/benefits
 * @export
 * @interface OtherFeesChargesPropertyInner
 */
export interface OtherFeesChargesPropertyInner {
    /**
     * TariffType which defines the fee and charges.
     * @type {string}
     * @memberof OtherFeesChargesPropertyInner
     */
    'TariffType'?: OtherFeesChargesPropertyInnerTariffTypeEnum;
    /**
     * Name of the tariff
     * @type {string}
     * @memberof OtherFeesChargesPropertyInner
     */
    'TariffName'?: string;
    /**
     * 
     * @type {OtherTariffTypeProperty}
     * @memberof OtherFeesChargesPropertyInner
     */
    'OtherTariffType'?: OtherTariffTypeProperty;
    /**
     * Other fees/charges details
     * @type {Array<FeeChargeDetailPropertyInner>}
     * @memberof OtherFeesChargesPropertyInner
     */
    'FeeChargeDetail': Array<FeeChargeDetailPropertyInner>;
    /**
     * Details about any caps (maximum charges) that apply to a particular or group of fee/charge
     * @type {Array<FeeChargeCapPropertyInner1>}
     * @memberof OtherFeesChargesPropertyInner
     */
    'FeeChargeCap'?: Array<FeeChargeCapPropertyInner1>;
}

type OtherFeesChargesPropertyInnerTariffTypeEnum = 'Electronic' | 'Mixed' | 'Other'


