/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty1 } from './other-application-frequency-property1';
import { OtherCalculationFrequencyProperty1 } from './other-calculation-frequency-property1';
import { OtherFeeRateTypeProperty } from './other-fee-rate-type-property';
import { OtherFeeTypeProperty } from './other-fee-type-property';
import { OverdraftFeeChargeCapPropertyInner1 } from './overdraft-fee-charge-cap-property-inner1';

/**
 * Details about the fees/charges
 * @export
 * @interface OverdraftFeeChargeDetailPropertyInner
 */
export interface OverdraftFeeChargeDetailPropertyInner {
    /**
     * Overdraft fee type
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'FeeType': OverdraftFeeChargeDetailPropertyInnerFeeTypeEnum;
    /**
     * Indicates whether fee and charges are negotiable
     * @type {boolean}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'NegotiableIndicator'?: boolean;
    /**
     * Indicates if the fee/charge is already covered by an \'Overdraft Control\' fee or not.
     * @type {boolean}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'OverdraftControlIndicator'?: boolean;
    /**
     * Every additional tranche of an overdraft balance to which an overdraft fee is applied
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'IncrementalBorrowingAmount'?: string;
    /**
     * Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'FeeRate'?: string;
    /**
     * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'FeeRateType'?: OverdraftFeeChargeDetailPropertyInnerFeeRateTypeEnum;
    /**
     * Frequency at which the overdraft charge is applied to the account
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'ApplicationFrequency': OverdraftFeeChargeDetailPropertyInnerApplicationFrequencyEnum;
    /**
     * How often is the overdraft fee/charge calculated for the account.
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'CalculationFrequency'?: OverdraftFeeChargeDetailPropertyInnerCalculationFrequencyEnum;
    /**
     * Free text for capturing any other info related to Overdraft Fees Charge Details
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge. Capping can either be based on an amount (in gbp), an amount (in items) or a rate.
     * @type {Array<OverdraftFeeChargeCapPropertyInner1>}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'OverdraftFeeChargeCap'?: Array<OverdraftFeeChargeCapPropertyInner1>;
    /**
     * 
     * @type {OtherFeeTypeProperty}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'OtherFeeType'?: OtherFeeTypeProperty;
    /**
     * 
     * @type {OtherFeeRateTypeProperty}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty1}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty1;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty1}
     * @memberof OverdraftFeeChargeDetailPropertyInner
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty1;
}

type OverdraftFeeChargeDetailPropertyInnerFeeTypeEnum = 'ArrangedOverdraft' | 'AnnualReview' | 'EmergencyBorrowing' | 'BorrowingItem' | 'OverdraftRenewal' | 'OverdraftSetup' | 'Surcharge' | 'TempOverdraft' | 'UnauthorisedBorrowing' | 'UnauthorisedPaidTrans' | 'Other' | 'UnauthorisedUnpaidTrans'
type OverdraftFeeChargeDetailPropertyInnerFeeRateTypeEnum = 'Gross' | 'Other'
type OverdraftFeeChargeDetailPropertyInnerApplicationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type OverdraftFeeChargeDetailPropertyInnerCalculationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'


