/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftFeesChargesPropertyInner2 } from './overdraft-fees-charges-property-inner2';

/**
 * Provides overdraft details for a specific tier or band
 * @export
 * @interface OverdraftTierBandPropertyInner1
 */
export interface OverdraftTierBandPropertyInner1 {
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'Identification'?: string;
    /**
     * Minimum value of Overdraft Tier/Band
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'TierValueMin': string;
    /**
     * Maximum value of Overdraft Tier/Band
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'TierValueMax'?: string;
    /**
     * Interest charged on whole amount or tiered/banded
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'OverdraftInterestChargingCoverage'?: OverdraftTierBandPropertyInner1OverdraftInterestChargingCoverageEnum;
    /**
     * Indicates that a bank provides the overdraft limit up to TierValueMIn to all customers automatically
     * @type {boolean}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'BankGuaranteedIndicator'?: boolean;
    /**
     * EAR means Effective Annual Rate and/or Equivalent Annual Rate (frequently used interchangeably), being the actual annual interest rate of an Overdraft.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'EAR'?: string;
    /**
     * An annual percentage rate (APR) is the annual rate charged for borrowing or earned through an investment. APR is expressed as a percentage that represents the actual yearly cost of funds over the term of a loan. This includes any fees or additional costs associated with the transaction but does not take compounding into account.
     * @type {string}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'RepresentativeAPR'?: string;
    /**
     * Optional additional notes to supplement the Tier/band details
     * @type {Array<string>}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * Overdraft fees and charges
     * @type {Array<OverdraftFeesChargesPropertyInner2>}
     * @memberof OverdraftTierBandPropertyInner1
     */
    'OverdraftFeesCharges'?: Array<OverdraftFeesChargesPropertyInner2>;
}

type OverdraftTierBandPropertyInner1OverdraftInterestChargingCoverageEnum = 'Tiered' | 'Whole'


