/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OverdraftFeesChargesPropertyInner1 } from './overdraft-fees-charges-property-inner1';
import { OverdraftTierBandPropertyInner } from './overdraft-tier-band-property-inner';

/**
 * Tier band set details
 * @export
 * @interface OverdraftTierBandSetPropertyInner
 */
export interface OverdraftTierBandSetPropertyInner {
    /**
     * The methodology of how overdraft is charged. It can be: \'Whole\'  Where the same charge/rate is applied to the entirety of the overdraft balance (where charges are applicable).  \'Tiered\' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount tiers defined by the lending financial organisation \'Banded\' Where different charges/rates are applied dependent on overdraft maximum and minimum balance amount bands defined by a government organisation.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'TierBandMethod': OverdraftTierBandSetPropertyInnerTierBandMethodEnum;
    /**
     * An overdraft can either be \'committed\' which means that the facility cannot be withdrawn without reasonable notification before it\'s agreed end date, or \'on demand\' which means that the financial institution can demand repayment at any point in time.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'OverdraftType'?: OverdraftTierBandSetPropertyInnerOverdraftTypeEnum;
    /**
     * Unique and unambiguous identification of a  Tier Band for a overdraft product.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'Identification'?: string;
    /**
     * Indicates if the Overdraft is authorised (Y) or unauthorised (N)
     * @type {boolean}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'AuthorisedIndicator'?: boolean;
    /**
     * When a customer exceeds their credit limit, a financial institution will not charge the customer unauthorised overdraft charges if they do not exceed by more than the buffer amount. Note: Authorised overdraft charges may still apply.
     * @type {string}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'BufferAmount'?: string;
    /**
     * Optional additional notes to supplement the overdraft Tier Band Set details
     * @type {Array<string>}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * Provides overdraft details for a specific tier or band
     * @type {Array<OverdraftTierBandPropertyInner>}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'OverdraftTierBand': Array<OverdraftTierBandPropertyInner>;
    /**
     * Overdraft fees and charges details
     * @type {Array<OverdraftFeesChargesPropertyInner1>}
     * @memberof OverdraftTierBandSetPropertyInner
     */
    'OverdraftFeesCharges'?: Array<OverdraftFeesChargesPropertyInner1>;
}

type OverdraftTierBandSetPropertyInnerTierBandMethodEnum = 'Banded' | 'Tiered' | 'Whole'
type OverdraftTierBandSetPropertyInnerOverdraftTypeEnum = 'Committed' | 'OnDemand'


