/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty2 } from './other-application-frequency-property2';
import { OtherCalculationFrequencyProperty2 } from './other-calculation-frequency-property2';
import { OtherFeeRateTypeProperty1 } from './other-fee-rate-type-property1';
import { OtherFeeTypeProperty1 } from './other-fee-type-property1';
import { OverdraftFeeChargeCapPropertyInner3 } from './overdraft-fee-charge-cap-property-inner3';

/**
 * Details about the fees/charges
 * @export
 * @interface OverdraftFeeChargeDetailPropertyInner1
 */
export interface OverdraftFeeChargeDetailPropertyInner1 {
    /**
     * Overdraft fee type
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeType': OverdraftFeeChargeDetailPropertyInner1FeeTypeEnum;
    /**
     * Indicates whether fee and charges are negotiable
     * @type {boolean}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'NegotiableIndicator'?: boolean;
    /**
     * Indicates if the fee/charge is already covered by an \'Overdraft Control\' fee or not.
     * @type {boolean}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OverdraftControlIndicator'?: boolean;
    /**
     * Every additional tranche of an overdraft balance to which an overdraft fee is applied
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'IncrementalBorrowingAmount'?: string;
    /**
     * Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeRate'?: string;
    /**
     * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'FeeRateType'?: OverdraftFeeChargeDetailPropertyInner1FeeRateTypeEnum;
    /**
     * Frequency at which the overdraft charge is applied to the account
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'ApplicationFrequency': OverdraftFeeChargeDetailPropertyInner1ApplicationFrequencyEnum;
    /**
     * How often is the overdraft fee/charge calculated for the account.
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'CalculationFrequency'?: OverdraftFeeChargeDetailPropertyInner1CalculationFrequencyEnum;
    /**
     * Free text for capturing any other info related to Overdraft Fees Charge Details
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * Details about any caps (maximum charges) that apply to a particular fee/charge. Capping can either be based on an amount (in gbp), an amount (in items) or a rate.
     * @type {Array<OverdraftFeeChargeCapPropertyInner3>}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OverdraftFeeChargeCap'?: Array<OverdraftFeeChargeCapPropertyInner3>;
    /**
     * 
     * @type {OtherFeeTypeProperty1}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherFeeType'?: OtherFeeTypeProperty1;
    /**
     * 
     * @type {OtherFeeRateTypeProperty1}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty1;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty2}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty2;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty2}
     * @memberof OverdraftFeeChargeDetailPropertyInner1
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty2;
}

type OverdraftFeeChargeDetailPropertyInner1FeeTypeEnum = 'ArrangedOverdraft' | 'AnnualReview' | 'EmergencyBorrowing' | 'BorrowingItem' | 'OverdraftRenewal' | 'OverdraftSetup' | 'Surcharge' | 'TempOverdraft' | 'UnauthorisedBorrowing' | 'UnauthorisedPaidTrans' | 'Other' | 'UnauthorisedUnpaidTrans'
type OverdraftFeeChargeDetailPropertyInner1FeeRateTypeEnum = 'Gross' | 'Other'
type OverdraftFeeChargeDetailPropertyInner1ApplicationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type OverdraftFeeChargeDetailPropertyInner1CalculationFrequencyEnum = 'OnClosing' | 'OnOpening' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAnniversary' | 'Other' | 'PerHundredPounds' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'


