/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty5 } from './other-application-frequency-property5';
import { OtherCalculationFrequencyProperty5 } from './other-calculation-frequency-property5';
import { OtherFeeRateTypeProperty3 } from './other-fee-rate-type-property3';
import { OtherFeeTypeProperty3 } from './other-fee-type-property3';
import { OverdraftFeeChargeCapProperty } from './overdraft-fee-charge-cap-property';

/**
 * Details about the fees/charges
 * @export
 * @interface OverdraftFeeChargeDetailPropertyInner2
 */
export interface OverdraftFeeChargeDetailPropertyInner2 {
    /**
     * Overdraft fee type
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'FeeType': OverdraftFeeChargeDetailPropertyInner2FeeTypeEnum;
    /**
     * Specifies for the overdraft control feature/benefit
     * @type {boolean}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'OverdraftControlIndicator'?: boolean;
    /**
     * Every additional tranche of an overdraft balance to which an overdraft fee is applied
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'IncrementalBorrowingAmount'?: string;
    /**
     * Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'FeeRate'?: string;
    /**
     * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'FeeRateType'?: OverdraftFeeChargeDetailPropertyInner2FeeRateTypeEnum;
    /**
     * Frequency at which the overdraft charge is applied to the account
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'ApplicationFrequency': OverdraftFeeChargeDetailPropertyInner2ApplicationFrequencyEnum;
    /**
     * How often is the overdraft fee/charge calculated for the account.
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'CalculationFrequency'?: OverdraftFeeChargeDetailPropertyInner2CalculationFrequencyEnum;
    /**
     * Free text for capturing any other info related to Overdraft Fees Charge Details
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherFeeTypeProperty3}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'OtherFeeType'?: OtherFeeTypeProperty3;
    /**
     * 
     * @type {OtherFeeRateTypeProperty3}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty3;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty5}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty5;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty5}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty5;
    /**
     * 
     * @type {OverdraftFeeChargeCapProperty}
     * @memberof OverdraftFeeChargeDetailPropertyInner2
     */
    'OverdraftFeeChargeCap'?: OverdraftFeeChargeCapProperty;
}

type OverdraftFeeChargeDetailPropertyInner2FeeTypeEnum = 'ArrangedOverdraft' | 'EmergencyBorrowing' | 'BorrowingItem' | 'OverdraftRenewal' | 'AnnualReview' | 'OverdraftSetup' | 'Surcharge' | 'TempOverdraft' | 'UnauthorisedBorrowing' | 'UnauthorisedPaidTrans' | 'Other' | 'UnauthorisedUnpaidTrans'
type OverdraftFeeChargeDetailPropertyInner2FeeRateTypeEnum = 'LinkedBaseRate' | 'Gross' | 'Net' | 'Other'
type OverdraftFeeChargeDetailPropertyInner2ApplicationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type OverdraftFeeChargeDetailPropertyInner2CalculationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'


