/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty6 } from './other-application-frequency-property6';
import { OtherCalculationFrequencyProperty6 } from './other-calculation-frequency-property6';
import { OtherFeeRateTypeProperty4 } from './other-fee-rate-type-property4';
import { OtherFeeTypeProperty4 } from './other-fee-type-property4';
import { OverdraftFeeChargeCapProperty1 } from './overdraft-fee-charge-cap-property1';

/**
 * Details about the fees/charges
 * @export
 * @interface OverdraftFeeChargeDetailPropertyInner3
 */
export interface OverdraftFeeChargeDetailPropertyInner3 {
    /**
     * Overdraft fee type
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'FeeType': OverdraftFeeChargeDetailPropertyInner3FeeTypeEnum;
    /**
     * Specifies for the overdraft control feature/benefit
     * @type {boolean}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'OverdraftControlIndicator'?: boolean;
    /**
     * Every additional tranche of an overdraft balance to which an overdraft fee is applied
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'IncrementalBorrowingAmount'?: string;
    /**
     * Amount charged for an overdraft fee/charge (where it is charged in terms of an amount rather than a rate)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'FeeAmount'?: string;
    /**
     * Rate charged for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'FeeRate'?: string;
    /**
     * Rate type for overdraft fee/charge (where it is charged in terms of a rate rather than an amount)
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'FeeRateType'?: OverdraftFeeChargeDetailPropertyInner3FeeRateTypeEnum;
    /**
     * Frequency at which the overdraft charge is applied to the account
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'ApplicationFrequency': OverdraftFeeChargeDetailPropertyInner3ApplicationFrequencyEnum;
    /**
     * How often is the overdraft fee/charge calculated for the account.
     * @type {string}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'CalculationFrequency'?: OverdraftFeeChargeDetailPropertyInner3CalculationFrequencyEnum;
    /**
     * Free text for capturing any other info related to Overdraft Fees Charge Details
     * @type {Array<string>}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherFeeTypeProperty4}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'OtherFeeType'?: OtherFeeTypeProperty4;
    /**
     * 
     * @type {OtherFeeRateTypeProperty4}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'OtherFeeRateType'?: OtherFeeRateTypeProperty4;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty6}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty6;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty6}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty6;
    /**
     * 
     * @type {OverdraftFeeChargeCapProperty1}
     * @memberof OverdraftFeeChargeDetailPropertyInner3
     */
    'OverdraftFeeChargeCap'?: OverdraftFeeChargeCapProperty1;
}

type OverdraftFeeChargeDetailPropertyInner3FeeTypeEnum = 'ArrangedOverdraft' | 'EmergencyBorrowing' | 'BorrowingItem' | 'OverdraftRenewal' | 'AnnualReview' | 'OverdraftSetup' | 'Surcharge' | 'TempOverdraft' | 'UnauthorisedBorrowing' | 'UnauthorisedPaidTrans' | 'Other' | 'UnauthorisedUnpaidTrans'
type OverdraftFeeChargeDetailPropertyInner3FeeRateTypeEnum = 'LinkedBaseRate' | 'Gross' | 'Net' | 'Other'
type OverdraftFeeChargeDetailPropertyInner3ApplicationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'
type OverdraftFeeChargeDetailPropertyInner3CalculationFrequencyEnum = 'AccountClosing' | 'AccountOpening' | 'AcademicTerm' | 'ChargingPeriod' | 'Daily' | 'PerItem' | 'Monthly' | 'OnAccountAnniversary' | 'Other' | 'PerHour' | 'PerOccurrence' | 'PerSheet' | 'PerTransaction' | 'PerTransactionAmount' | 'PerTransactionPercentage' | 'Quarterly' | 'SixMonthly' | 'StatementMonthly' | 'Weekly' | 'Yearly'


