/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductDetailsProperty
 */
export interface ProductDetailsProperty {
    /**
     * Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another.  Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  With respect to BCA products, they are segmented in relation to different markets that they wish to focus on. 
     * @type {Array<string>}
     * @memberof ProductDetailsProperty
     */
    'Segment'?: Array<ProductDetailsPropertySegmentEnum>;
    /**
     * The length/duration of the fee free period
     * @type {number}
     * @memberof ProductDetailsProperty
     */
    'FeeFreeLength'?: number;
    /**
     * The unit of period (days, weeks, months etc.) of the promotional length
     * @type {string}
     * @memberof ProductDetailsProperty
     */
    'FeeFreeLengthPeriod'?: ProductDetailsPropertyFeeFreeLengthPeriodEnum;
    /**
     * Optional additional notes to supplement the Core product details
     * @type {Array<string>}
     * @memberof ProductDetailsProperty
     */
    'Notes'?: Array<string>;
}

type ProductDetailsPropertySegmentEnum = 'ClientAccount' | 'Standard' | 'NonCommercialChaitiesClbSoc' | 'NonCommercialPublicAuthGovt' | 'Religious' | 'SectorSpecific' | 'Startup' | 'Switcher'
type ProductDetailsPropertyFeeFreeLengthPeriodEnum = 'Day' | 'Half Year' | 'Month' | 'Quarter' | 'Week' | 'Year'


