/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty } from './other-application-frequency-property';
import { OtherBankInterestTypeProperty } from './other-bank-interest-type-property';
import { OtherCalculationFrequencyProperty } from './other-calculation-frequency-property';

/**
 * Tier Band Details
 * @export
 * @interface TierBandPropertyInner
 */
export interface TierBandPropertyInner {
    /**
     * Unique and unambiguous identification of a  Tier Band for a BCA.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'Identification'?: string;
    /**
     * Minimum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'TierValueMinimum': string;
    /**
     * Maximum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'TierValueMaximum'?: string;
    /**
     * How often is credit interest calculated for the account.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'CalculationFrequency'?: TierBandPropertyInnerCalculationFrequencyEnum;
    /**
     * How often is interest applied to the BCA for this tier/band i.e. how often the financial institution pays accumulated interest to the customer\'s BCA.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'ApplicationFrequency': TierBandPropertyInnerApplicationFrequencyEnum;
    /**
     * Amount on which Interest applied.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'DepositInterestAppliedCoverage'?: TierBandPropertyInnerDepositInterestAppliedCoverageEnum;
    /**
     * Type of interest rate, Fixed or Variable
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'FixedVariableInterestRateType': TierBandPropertyInnerFixedVariableInterestRateTypeEnum;
    /**
     * The annual equivalent rate (AER) is interest that is calculated under the assumption that any interest paid is combined with the original balance and the next interest payment will be based on the slightly higher account balance. Overall, this means that interest can be compounded several times in a year depending on the number of times that interest payments are made.   Read more: Annual Equivalent Rate (AER) http://www.investopedia.com/terms/a/aer.asp#ixzz4gfR7IO1A
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'AER': string;
    /**
     * Interest rate types, other than AER, which financial institutions may use to describe the annual interest rate payable to the BCA.
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'BankInterestRateType'?: TierBandPropertyInnerBankInterestRateTypeEnum;
    /**
     * Bank Interest for the BCA product
     * @type {string}
     * @memberof TierBandPropertyInner
     */
    'BankInterestRate'?: string;
    /**
     * Optional additional notes to supplement the Tier Band details
     * @type {Array<string>}
     * @memberof TierBandPropertyInner
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherBankInterestTypeProperty}
     * @memberof TierBandPropertyInner
     */
    'OtherBankInterestType'?: OtherBankInterestTypeProperty;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty}
     * @memberof TierBandPropertyInner
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty}
     * @memberof TierBandPropertyInner
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty;
}

type TierBandPropertyInnerCalculationFrequencyEnum = 'Daily' | 'HalfYearly' | 'Monthly' | 'Other' | 'Quarterly' | 'PerStatementDate' | 'Weekly' | 'Yearly'
type TierBandPropertyInnerApplicationFrequencyEnum = 'Daily' | 'HalfYearly' | 'Monthly' | 'Other' | 'Quarterly' | 'PerStatementDate' | 'Weekly' | 'Yearly'
type TierBandPropertyInnerDepositInterestAppliedCoverageEnum = 'Banded' | 'Tiered' | 'Whole'
type TierBandPropertyInnerFixedVariableInterestRateTypeEnum = 'Fixed' | 'Variable'
type TierBandPropertyInnerBankInterestRateTypeEnum = 'Gross' | 'Other'


