/*
Account Information API

In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319)


The version of the OpenAPI document: 3.1.11


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OtherApplicationFrequencyProperty4 } from './other-application-frequency-property4';
import { OtherBankInterestTypeProperty1 } from './other-bank-interest-type-property1';
import { OtherCalculationFrequencyProperty4 } from './other-calculation-frequency-property4';

/**
 * Tier Band Details
 * @export
 * @interface TierBandPropertyInner1
 */
export interface TierBandPropertyInner1 {
    /**
     * Unique and unambiguous identification of a  Tier Band for a PCA.
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'Identification'?: string;
    /**
     * Minimum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'TierValueMinimum': string;
    /**
     * Maximum deposit value for which the credit interest tier applies.
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'TierValueMaximum'?: string;
    /**
     * How often is credit interest calculated for the account.
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'CalculationFrequency'?: TierBandPropertyInner1CalculationFrequencyEnum;
    /**
     * How often is interest applied to the PCA for this tier/band i.e. how often the financial institution pays accumulated interest to the customer\'s PCA.
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'ApplicationFrequency': TierBandPropertyInner1ApplicationFrequencyEnum;
    /**
     * Amount on which Interest applied.
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'DepositInterestAppliedCoverage'?: TierBandPropertyInner1DepositInterestAppliedCoverageEnum;
    /**
     * Type of interest rate, Fixed or Variable
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'FixedVariableInterestRateType': TierBandPropertyInner1FixedVariableInterestRateTypeEnum;
    /**
     * The annual equivalent rate (AER) is interest that is calculated under the assumption that any interest paid is combined with the original balance and the next interest payment will be based on the slightly higher account balance. Overall, this means that interest can be compounded several times in a year depending on the number of times that interest payments are made.   Read more: Annual Equivalent Rate (AER) http://www.investopedia.com/terms/a/aer.asp#ixzz4gfR7IO1A
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'AER': string;
    /**
     * Interest rate types, other than AER, which financial institutions may use to describe the annual interest rate payable to the PCA.
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'BankInterestRateType'?: TierBandPropertyInner1BankInterestRateTypeEnum;
    /**
     * Bank Interest for the PCA product
     * @type {string}
     * @memberof TierBandPropertyInner1
     */
    'BankInterestRate'?: string;
    /**
     * Optional additional notes to supplement the Tier Band details
     * @type {Array<string>}
     * @memberof TierBandPropertyInner1
     */
    'Notes'?: Array<string>;
    /**
     * 
     * @type {OtherBankInterestTypeProperty1}
     * @memberof TierBandPropertyInner1
     */
    'OtherBankInterestType'?: OtherBankInterestTypeProperty1;
    /**
     * 
     * @type {OtherApplicationFrequencyProperty4}
     * @memberof TierBandPropertyInner1
     */
    'OtherApplicationFrequency'?: OtherApplicationFrequencyProperty4;
    /**
     * 
     * @type {OtherCalculationFrequencyProperty4}
     * @memberof TierBandPropertyInner1
     */
    'OtherCalculationFrequency'?: OtherCalculationFrequencyProperty4;
}

type TierBandPropertyInner1CalculationFrequencyEnum = 'PerAcademicTerm' | 'Daily' | 'HalfYearly' | 'Monthly' | 'Other' | 'Quarterly' | 'PerStatementDate' | 'Weekly' | 'Yearly'
type TierBandPropertyInner1ApplicationFrequencyEnum = 'PerAcademicTerm' | 'Daily' | 'HalfYearly' | 'Monthly' | 'Other' | 'Quarterly' | 'PerStatementDate' | 'Weekly' | 'Yearly'
type TierBandPropertyInner1DepositInterestAppliedCoverageEnum = 'Tiered' | 'Whole'
type TierBandPropertyInner1FixedVariableInterestRateTypeEnum = 'Fixed' | 'Variable'
type TierBandPropertyInner1BankInterestRateTypeEnum = 'LinkedBaseRate' | 'Gross' | 'Net' | 'Other'


